language: java
before_install:
- rvm install 2.0.0
- gem install travis-custom-deploy
script: mvn -f org.eventb.texteditor.parent/pom.xml clean verify
after_success:
- travis-custom-deploy sftp org.eventb.texteditor.repository/target/repository/
env:
  global:
  - secure: YCES4StrYD8U1i1868rgd16vM4ken/RAIMC/1/QJ0j7TdC6xATDo/uYTGiKMMo+hzZUcoLCVFAVzkZSriZbxngEkia1U+mOPKOEm+sPEhynea6I+TgkinYBakDYNlC1lAah48aBOp+L74J352LZHKH+H0mncRfJwC/e5zba59HU=
  - secure: Ch0wjR1Nr4sMW3vl1QV4MxMBp+ArVXR4VX9jxa15z0SbiuSosDpihJRP3j/MibnCMLb+Gn+HEloDxuGicqGD8xgnI1XUkVIykQsvEYp21YMBp1WU5tY/N4xM85RBJ+DudoQb+vKQ2OwpSmUhlelUIE2XmW0WtPdN57G/p87fNXo=
  - secure: RRDTEE1zALhonAvzYY7cTzWOO3Q8Isp9eZhY45dH89LxJu1AJx6U8R5me4LfVgEhLPF5/1G9M8ZVoog+xVNUrU7pOq3W+NH1YDz2AugOaN4pdNMNHwGkn0uzsZU9V1Obh6wf/fCsIgddsW/34Rw1Xekd0dpFOvvCE8oNRxE3fiY=
  - secure: L49gqZw95AxxDTI5IoNfsf9d4knS+M85PpQKbSWsz5UaUp6J7q/WEDK4C4Kso7kF6nC/U8plKAiQ2CzVkZpsB7Z6jeQ5XpWYqn257eN40g0ZPLgXaavi2PSwcBZWwE6f0atNKXAdpPd6tzUr8aaWlSdqQVTjkAhWl7138dalh1Q=
