<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.eventb.texteditor</groupId>
	<artifactId>org.eventb.texteditor.parent</artifactId>
	<version>3.6.1-SNAPSHOT</version>

	<packaging>pom</packaging>

	<!-- this is the parent POM from which all modules inherit common settings -->
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<repositories>
		<!-- configure p2 repository to resolve against -->
		<repository>
			<id>eclipse</id>
			<layout>p2</layout>
			<!-- Eclipse 4.38 -->
			<url>https://download.eclipse.org/releases/2025-12/</url>
		</repository>

		<repository>
			<id>rodin_core</id>
			<layout>p2</layout>
			<url>https://rodin-b-sharp.sourceforge.net/core-updates/3.10/</url>
		</repository>

		<repository>
			<id>rodin_plugins</id>
			<layout>p2</layout>
			<url>https://rodin-b-sharp.sourceforge.net/updates/</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>5.0.2</version>
				<configuration>
					<executionEnvironment>JavaSE-21</executionEnvironment>
				</configuration>
			</plugin>
			<plugin>
				<!-- enable tycho build extension -->
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>5.0.2</version>
				<extensions>true</extensions>
			</plugin>
		</plugins>
	</build>

	<!-- the modules that should be built together -->
	<modules>
		<module>../org.eventb.texteditor.feature</module>
		<module>../org.eventb.texteditor.parsers</module>
		<module>../org.eventb.texteditor.repository</module>
		<module>../org.eventb.texteditor.ui</module>
		<module>../org.eventb.texttools</module>
	</modules>
</project>
